Import of pkgsrc-2015Q1

diff --git a/bootstrap/bootstrap b/bootstrap/bootstrap
--- a/bootstrap/bootstrap
+++ b/bootstrap/bootstrap
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# $NetBSD: bootstrap,v 1.204 2014/03/14 21:52:13 ryoon Exp $
+# $NetBSD: bootstrap,v 1.215 2014/12/04 10:36:02 jperkin Exp $
 #
 # Copyright (c) 2001-2011 Alistair Crooks <agc@NetBSD.org>
 # All rights reserved.
@@ -58,9 +58,11 @@ usage="Usage: $0 "'
     [ --binary-kit <tarball> ]
     [ --binary-macpkg <pkg> ]
     [ --compiler <compiler> ]
+    [ --cwrappers ]
     [ --full ]
     [ --gzip-binary-kit <tarball> ]
     [ --help ]
+    [ --make-jobs <num> ]
     [ --mk-fragment <mk.conf> ]
     [ --pkgdbdir <pkgdbdir> ]
     [ --pkginfodir <pkginfodir> ]
@@ -159,7 +161,9 @@ EOF
 
 	cat >${wrkdir}/$$.c <<EOF
 #ifdef __GNUC__
+#ifndef __clang__
 indeed
+#endif
 #endif
 EOF
 	compiler_is_gnu=`${testcc:-cc} -E ${wrkdir}/$$.c 2>/dev/null | grep -c indeed`
@@ -386,10 +390,12 @@ pkgmandir=
 sysconfdir=
 varbase=
 
-full=no
 compiler=""
-quiet=no
+cwrappers=no
+full=no
+make_jobs=1
 mk_fragment=
+quiet=no
 
 while [ $# -gt 0 ]; do
 	case $1 in
@@ -411,6 +417,7 @@ while [ $# -gt 0 ]; do
 	--compiler)	compiler="$2"; shift ;;
 	--abi=*)	abi=`get_optarg "$1"` ;;
 	--abi)		abi="$2"; shift ;;
+	--cwrappers)	cwrappers=yes ;;
 	--unprivileged | --ignore-user-check) unprivileged=yes ;;
 	--prefer-pkgsrc=*)
 			prefer_pkgsrc=`get_optarg "$1"` ;;
@@ -433,6 +440,8 @@ while [ $# -gt 0 ]; do
 			binary_macpkg=`get_optarg "$1"` ;;
 	--binary-macpkg)
 			binary_macpkg="$2"; shift ;;
+	--make-jobs=*)	make_jobs=`get_optarg "$1"` ;;
+	--make-jobs)	make_jobs="$2"; shift ;;
 	--full)		full=yes ;;
 	--quiet)	quiet=yes ;;
 	--help)		echo "$usage"; exit ;;
@@ -479,7 +488,6 @@ fi
 
 overpath=""
 root_user=root
-bmakexenv=
 bmakexargs=
 need_extras=no
 set_machine_arch=no
@@ -520,11 +528,12 @@ Darwin)
 	need_sed=no
 	set_opsys=no
 	machine_arch=`uname -p`
-	CC=${CC:-"gcc -isystem /usr/include"}; export CC
+	CC=${CC:-"cc -isystem /usr/include"}; export CC
+	check_compiler=yes
 	osrev=`uname -r`
 	macosx_version=`echo $osrev | awk -F . '{ print "10."$1-4; }'`
 	case "$macosx_version" in
-	10.[7-8])
+	10.[7-9])
 		packagemaker=/Applications/PackageMaker.app/Contents/MacOS/PackageMaker
 		;;
 	10.[0-4])
@@ -535,7 +544,7 @@ Darwin)
 		;;
 	esac
 	case "$macosx_version" in
-	10.[8-9])
+	10.[8-9]|10.10)
 		need_awk=yes
 		need_sed=yes
 		;;
@@ -614,8 +623,8 @@ Interix)
 		mkdir -p "$@" # allows umask to take effect
 	}
 	default_install_mode=0775
-	root_user=`id -u`
-	root_group=131616
+	root_user=`id -un`
+	root_group=+Administrators
 	case `uname -r` in
 	3.* | 5.*)
 		need_bsd_install=yes
@@ -658,7 +667,6 @@ IRIX*)
 	set_opsys=yes
 	machine_arch=mipseb
 	bmakexargs="MACHINE_ARCH=$machine_arch"
-	bmakexenv="MAKE=pmake"
 	check_compiler=yes
 	if [ `uname -r` -lt 6 ]; then
 # IRIX 5's mkdir bails out with an error when trying to create with the -p
@@ -842,6 +850,11 @@ no)
 	make_quiet_flags=""
 esac
 
+test ${make_jobs} -gt 0 2>/dev/null
+if [ $? -ne 0 ]; then
+	die "ERROR: --make-jobs must be a positive integer argument"
+fi
+
 # export OPSYS and MACHINE_ARCH for pkg_install. we only set
 # MACHINE_ARCH on platforms where we override bmake's value.
 OPSYS=${opsys}
@@ -981,6 +994,9 @@ clang)
 	echo "CC=			clang"     >> ${TARGET_MKCONF}
 	echo "CXX=			clang++"   >> ${TARGET_MKCONF}
 	echo "CPP=			\${CC} -E" >> ${TARGET_MKCONF}
+	if [ -z "$CLANGBASE" -a -f "/usr/bin/clang" ]; then
+		CLANGBASE="/usr"
+	fi
 	if [ -n "$CLANGBASE" -o -f "/bin/clang" ]; then
 		echo "CLANGBASE=		$CLANGBASE" >> ${TARGET_MKCONF}
 	fi
@@ -1018,6 +1034,13 @@ fi
 
 BOOTSTRAP_MKCONF=${wrkdir}/mk.conf
 cp ${TARGET_MKCONF} ${BOOTSTRAP_MKCONF}
+
+case "$cwrappers" in
+yes)
+	echo "USE_CWRAPPERS=		yes" >> ${TARGET_MKCONF}
+	echo "" >> ${TARGET_MKCONF}
+	;;
+esac
 
 # On all Debian GNU/kFreeBSD 7, /bin/sh is a symlink to /bin/dash, and
 # use /bin/bash.
@@ -1074,9 +1097,9 @@ $shprog ./bootstrap.sh)"
 bootstrap_bmake() {
 	echo_msg "Bootstrapping bmake"
 	copy_src $pkgsrcdir/devel/bmake/files bmake
-	run_cmd "chmod u+x $wrkdir/bmake/configure"
-	run_cmd "(cd $wrkdir/bmake && env $bmakexenv $shprog ./boot-strap $configure_quiet_flags -q -o bootstrap.$opsys --prefix=$wrkdir --sysconfdir=$wrkdir --mksrc none --with-default-sys-path="$wrkdir/share/mk" $bmakexargs)"
-	run_cmd "$install_sh -c -o $user -g $group -m 755 $wrkdir/bmake/bootstrap.$opsys/bmake $wrkdir/bin/bmake"
+	run_cmd "(cd $wrkdir/bmake && $shprog configure $configure_quiet_flags --with-default-sys-path=$wrkdir/share/mk --prefix=$wrkdir $bmakexargs)"
+	run_cmd "(cd $wrkdir/bmake && $shprog make-bootstrap.sh)"
+	run_cmd "$install_sh -c -o $user -g $group -m 755 $wrkdir/bmake/bmake $wrkdir/bin/bmake"
 }
 bootstrap_bmake
 
@@ -1085,14 +1108,14 @@ bmake="$wrkdir/bin/bmake $make_quiet_flags"
 # build libnbcompat
 echo_msg "Building libnbcompat"
 copy_src $pkgsrcdir/pkgtools/libnbcompat/files libnbcompat
-run_cmd "(cd $wrkdir/libnbcompat; $shprog ./configure $configure_quiet_flags -C --prefix=$prefix --infodir=$infodir --mandir=$mandir --sysconfdir=$sysconfdir --enable-bsd-getopt --enable-db && $bmake $make_quiet_flags)"
+run_cmd "(cd $wrkdir/libnbcompat; $shprog ./configure $configure_quiet_flags -C --prefix=$prefix --infodir=$infodir --mandir=$mandir --sysconfdir=$sysconfdir --enable-bsd-getopt --enable-db && $bmake -j$make_jobs)"
 
 # bootstrap ksh if necessary
 case "$need_ksh" in
 yes)	echo_msg "Bootstrapping ksh"
 	copy_src $pkgsrcdir/shells/pdksh/files ksh
 	test -n "$CC" || CC=gcc	# default to gcc if no compiler is specified
-	run_cmd "(cd $wrkdir/ksh && env $BSTRAP_ENV $shprog ./configure $configure_quiet_flags --prefix=$prefix --infodir=$infodir --mandir=$mandir --sysconfdir=$sysconfdir && $bmake)"
+	run_cmd "(cd $wrkdir/ksh && env $BSTRAP_ENV $shprog ./configure $configure_quiet_flags --prefix=$prefix --infodir=$infodir --mandir=$mandir --sysconfdir=$sysconfdir && $bmake -j$make_jobs)"
 	run_cmd "$install_sh -c -o $user -g $group -m 755 $wrkdir/ksh/ksh $wrkdir/bin/pdksh"
 	echo "TOOLS_PLATFORM.sh?=		$prefix/bin/pdksh" >> ${TARGET_MKCONF}
 	echo "TOOLS_PLATFORM.sh?=		$wrkdir/bin/pdksh" >> ${BOOTSTRAP_MKCONF}
@@ -1110,7 +1133,7 @@ case "$need_awk" in
 yes)	echo_msg "Bootstrapping awk"
 	copy_src $pkgsrcdir/lang/nawk/files awk
 	test -n "$CC" || CC=gcc	# default to gcc if no compiler is specified
-	run_cmd "(cd $wrkdir/awk && $bmake -f Makefile CC=\"${CC}\" CFLAGS=\"${CFLAGS}\")"
+	run_cmd "(cd $wrkdir/awk && $bmake -j$make_jobs -f Makefile CC=\"${CC}\" CFLAGS=\"${CFLAGS}\")"
 	run_cmd "$install_sh -c -o $user -g $group -m 755 $wrkdir/awk/a.out $wrkdir/bin/nawk"
 	echo "TOOLS_PLATFORM.awk?=		$prefix/bin/nawk" >> ${TARGET_MKCONF}
 	echo "TOOLS_PLATFORM.awk?=		$wrkdir/bin/nawk" >> ${BOOTSTRAP_MKCONF}
@@ -1121,7 +1144,7 @@ esac
 case "$need_sed" in
 yes)	echo_msg "Bootstrapping sed"
 	copy_src $pkgsrcdir/textproc/nbsed/files sed
-	run_cmd "(cd $wrkdir/sed; env $BSTRAP_ENV CPPFLAGS='$CPPFLAGS -I../libnbcompat' LDFLAGS='$LDFLAGS -L../libnbcompat' LIBS='$LIBS -lnbcompat' $shprog ./configure $configure_quiet_flags -C --prefix=$prefix --infodir=$infodir --mandir=$mandir --sysconfdir=$sysconfdir --program-transform-name='s,sed,nbsed,' && $bmake)"
+	run_cmd "(cd $wrkdir/sed; env $BSTRAP_ENV CPPFLAGS='$CPPFLAGS -I../libnbcompat' LDFLAGS='$LDFLAGS -L../libnbcompat' LIBS='$LIBS -lnbcompat' $shprog ./configure $configure_quiet_flags -C --prefix=$prefix --infodir=$infodir --mandir=$mandir --sysconfdir=$sysconfdir --program-transform-name='s,sed,nbsed,' && $bmake -j$make_jobs)"
 	run_cmd "$install_sh -c -o $user -g $group -m 755 $wrkdir/sed/sed $wrkdir/bin/sed"
 	echo "TOOLS_PLATFORM.sed?=		$prefix/bin/nbsed" >> ${TARGET_MKCONF}
 	echo "TOOLS_PLATFORM.sed?=		$wrkdir/bin/sed" >> ${BOOTSTRAP_MKCONF}
@@ -1136,7 +1159,7 @@ CPPFLAGS='$CPPFLAGS -I../libnbcompat -I../../libnbcompat' \
 LDFLAGS='$LDFLAGS -L../libnbcompat -L../../libnbcompat' \
 LIBS='$LIBS -lnbcompat' $shprog ./configure $configure_quiet_flags -C \
 --enable-bootstrap --prefix=$prefix --sysconfdir=$sysconfdir \
---with-pkgdbdir=$pkgdbdir --infodir=$infodir --mandir=$mandir $pkg_install_args && $bmake)"
+--with-pkgdbdir=$pkgdbdir --infodir=$infodir --mandir=$mandir $pkg_install_args && $bmake -j$make_jobs)"
 run_cmd "$install_sh -c -o $user -g $group -m 755 $wrkdir/pkg_install/admin/pkg_admin $wrkdir/sbin/pkg_admin"
 run_cmd "$install_sh -c -o $user -g $group -m 755 $wrkdir/pkg_install/create/pkg_create $wrkdir/sbin/pkg_create"
 run_cmd "$install_sh -c -o $user -g $group -m 755 $wrkdir/pkg_install/info/pkg_info $wrkdir/sbin/pkg_info"
@@ -1213,7 +1236,7 @@ echo ".endif			# end pkgsrc settings" >> ${BOOTSTRAP_MKCONF}
 # build and register packages
 # usage: build_package <packagedirectory> [additional arguments]
 build_package() {
-	run_cmd "(cd $pkgsrcdir/$1 && $bmake USE_DESTDIR=no -DPKG_PRESERVE MAKECONF=${BOOTSTRAP_MKCONF} install)"
+	run_cmd "(cd $pkgsrcdir/$1 && $bmake MAKE_JOBS=${make_jobs} USE_DESTDIR=no -DPKG_PRESERVE MAKECONF=${BOOTSTRAP_MKCONF} install)"
 }
 
 #
diff --git a/multimedia/x264-devel/patches/patch-aa b/multimedia/x264-devel/patches/patch-aa
--- a/multimedia/x264-devel/patches/patch-aa
+++ b/multimedia/x264-devel/patches/patch-aa
@@ -1,19 +1,13 @@
-$NetBSD: patch-aa,v 1.17 2014/03/04 13:59:11 adam Exp $
+$NetBSD: patch-aa,v 1.20 2015/01/21 18:15:17 adam Exp $
 
-Clang does not support -falign-loops option.
+Add support for DragonFly.
+Use 'amd64' as a synonym for 'x86_64'.
+Avoid endian test failure for -flto.
+Do not force compiler optimisations.
 
---- configure.orig	2014-03-03 21:45:04.000000000 +0000
+--- configure.orig	2014-11-28 21:45:04.000000000 +0000
 +++ configure
-@@ -467,7 +467,7 @@ case $host_os in
-         ;;
-     darwin*)
-         SYS="MACOSX"
--        CFLAGS="$CFLAGS -falign-loops=16"
-+        CFLAGS="$CFLAGS"
-         libm="-lm"
-         if [ "$pic" = "no" ]; then
-             cc_check "" -mdynamic-no-pic && CFLAGS="$CFLAGS -mdynamic-no-pic"
-@@ -477,6 +477,10 @@ case $host_os in
+@@ -516,6 +516,10 @@ case $host_os in
          SYS="FREEBSD"
          libm="-lm"
          ;;
@@ -24,7 +18,7 @@ Clang does not support -falign-loops option.
      kfreebsd*-gnu)
          SYS="FREEBSD"
          define HAVE_MALLOC_H
-@@ -599,7 +603,7 @@ case $host_cpu in
+@@ -639,7 +643,7 @@ case $host_cpu in
              ASFLAGS="$ASFLAGS -f elf"
          fi
          ;;
@@ -32,24 +26,34 @@ Clang does not support -falign-loops option.
 +    x86_64|amd64)
          ARCH="X86_64"
          AS="yasm"
-         [ $compiler = GNU ] && CFLAGS="-m64 $CFLAGS" && LDFLAGS="-m64 $LDFLAGS"
-@@ -620,13 +624,14 @@ case $host_cpu in
+         AS_EXT=".asm"
+@@ -662,14 +666,15 @@ case $host_cpu in
          fi
          ;;
      powerpc|powerpc64)
 -        ARCH="PPC"
          if [ $asm = auto ] ; then
              define HAVE_ALTIVEC
-             AS="${AS-${cross_prefix}gcc}"
+             AS="${AS-${CC}}"
+             AS_EXT=".c"
              if [ $SYS = MACOSX ] ; then
-+	        ARCH="POWERPC"
++                ARCH="POWERPC"
                  CFLAGS="$CFLAGS -faltivec -fastf -mcpu=G4"
              else
-+	        ARCH="PPC"
++                ARCH="PPC"
                  CFLAGS="$CFLAGS -maltivec -mabi=altivec"
                  define HAVE_ALTIVEC_H
              fi
-@@ -777,7 +782,7 @@ fi
+@@ -817,7 +822,7 @@ ASFLAGS="$ASFLAGS -DSTACK_ALIGNMENT=$sta
+ # skip endianness check for Intel Compiler and MSVS, as all supported platforms are little. each have flags that will cause the check to fail as well
+ if [ $compiler = GNU ]; then
+     echo "int i[2] = {0x42494745,0}; double f[2] = {0x1.0656e6469616ep+102,0};" > conftest.c
+-    $CC $CFLAGS conftest.c -c -o conftest.o 2>/dev/null || die "endian test failed"
++    $CC $CPPFLAGS conftest.c -c -o conftest.o 2>/dev/null || die "endian test failed"
+     if (${cross_prefix}strings -a conftest.o | grep -q BIGE) && (${cross_prefix}strings -a conftest.o | grep -q FPendian) ; then
+         define WORDS_BIGENDIAN
+     elif !(${cross_prefix}strings -a conftest.o | grep -q EGIB && ${cross_prefix}strings -a conftest.o | grep -q naidnePF) ; then
+@@ -830,7 +835,7 @@ fi
  # pthread-win32 is lgpl, prevent its use if --disable-gpl is specified and targeting windows
  [ "$SYS" = "WINDOWS" -a "$gpl" = "no" -a "$thread" = "auto" ] && thread="win32"
  
@@ -58,7 +62,7 @@ Clang does not support -falign-loops option.
  if [ "$thread" = "auto" ]; then
      thread="no"
      case $SYS in
-@@ -986,10 +991,11 @@ fi
+@@ -1044,10 +1049,11 @@ fi
  cc_check "stdint.h" "" "uint32_t test_vec __attribute__ ((vector_size (16))) = {0,1,2,3};" && define HAVE_VECTOREXT
  
  if [ "$pic" = "yes" ] ; then
@@ -72,3 +76,21 @@ Clang does not support -falign-loops option.
      [ $SYS = SunOS -a "$ARCH" = "X86" ] && SOFLAGS="$SOFLAGS -mimpure-text"
  fi
  
+@@ -1061,8 +1067,6 @@ fi
+ 
+ if [ "$debug" = "yes" ]; then
+     CFLAGS="-O1 -g $CFLAGS"
+-else
+-    CFLAGS="-O3 -ffast-math $CFLAGS"
+ fi
+ 
+ if cc_check '' -fno-tree-vectorize ; then
+@@ -1154,7 +1158,7 @@ else # gcc/icc
+     DEPMM="$DEPMM -g0"
+     AR="$AR rc "
+     LD="$CC -o "
+-    LIBX264=libx264.a
++    LIBX264=libx264.la
+     [ -n "$RC" ] && RCFLAGS="$RCFLAGS -I. -o "
+ fi
+ [ $compiler != GNU ] && CFLAGS="$(cc_cflags $CFLAGS)"
diff --git a/net/libbind/patches/patch-aa b/net/libbind/patches/patch-aa
--- a/net/libbind/patches/patch-aa
+++ b/net/libbind/patches/patch-aa
@@ -1,19 +1,18 @@
-$NetBSD: patch-aa,v 1.2 2010/12/31 14:36:07 obache Exp $
+$NetBSD: patch-aa,v 1.4 2014/05/11 10:16:40 obache Exp $
+
+* regen with pkgsrc patches
 
 --- configure.orig	2009-03-05 01:37:31.000000000 +0000
 +++ configure
-@@ -25135,9 +25135,9 @@ case $use_libtool in
- 		O=lo
- 		A=la
- 		LIBTOOL_MKDEP_SED='s;\.o;\.lo;'
--		LIBTOOL_MODE_COMPILE='--mode=compile'
-+		LIBTOOL_MODE_COMPILE='--mode=compile --tag=CC'
- 		LIBTOOL_MODE_INSTALL='--mode=install'
--		LIBTOOL_MODE_LINK='--mode=link'
-+		LIBTOOL_MODE_LINK='--mode=link --tag=CC'
- 		;;
- 	*)
- 		O=o
+@@ -21891,7 +21891,7 @@ then
+ 		# currently work with bind9, but can be chosen with
+ 		# the --with-ptl2 option for those who wish to
+ 		# experiment with it.
+-		CC="gcc"
++		# CC="gcc"
+ 		{ echo "$as_me:$LINENO: checking which NetBSD thread library to use" >&5
+ echo $ECHO_N "checking which NetBSD thread library to use... $ECHO_C" >&6; }
+ 
 @@ -25928,7 +25928,7 @@ case "$host" in
  			PORT_NONBLOCK="#define PORT_NONBLOCK O_NDELAY"
  			PORT_DIR="port/cygwin";;
@@ -23,3 +22,120 @@ $NetBSD: patch-aa,v 1.2 2010/12/31 14:36:07 obache Exp $
  	*-osf*)		PORT_DIR="port/decunix";;
  	*-freebsd*)	PORT_DIR="port/freebsd";;
  	*-hpux9*)	PORT_DIR="port/hpux9";;
+@@ -32049,6 +32049,56 @@ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
++	cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++#undef _REENTRANT
++#define _REENTRANT
++#undef __USE_MISC
++#define __USE_MISC
++#include <netdb.h>
++void setprotoent_r (int, struct protoent_data *);
++
++int
++main ()
++{
++
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext
++if { (ac_try="$ac_compile"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_compile") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } && {
++	 test -z "$ac_c_werror_flag" ||
++	 test ! -s conftest.err
++       } && test -s conftest.$ac_objext; then
++  PROTO_R_SET_RESULT="#undef PROTO_R_SET_RESULT"
++PROTO_R_SET_RETURN="#define PROTO_R_SET_RETURN void"
++
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++
++fi
++
++rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+ 
+ fi
+ 
+@@ -33647,6 +33697,59 @@ else
+   echo "$as_me: failed program was:" >&5
+ sed 's/^/| /' conftest.$ac_ext >&5
+ 
++	cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++#undef _REENTRANT
++#define _REENTRANT
++#undef __USE_MISC
++#define __USE_MISC
++#include <netdb.h>
++void setservent_r(int, struct servent_data *);
++
++
++int
++main ()
++{
++
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext
++if { (ac_try="$ac_compile"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_compile") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } && {
++	 test -z "$ac_c_werror_flag" ||
++	 test ! -s conftest.err
++       } && test -s conftest.$ac_objext; then
++
++SERV_R_SET_RESULT="#undef SERV_R_SET_RESULT"
++SERV_R_SET_RETURN="#define SERV_R_SET_RETURN void"
++
++
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++
++fi
++
++rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+ 
+ fi
+ 
