Import of pkgsrc-2015Q3

diff --git a/mail/mutt/patches/patch-ab b/mail/mutt/patches/patch-ab
--- a/mail/mutt/patches/patch-ab
+++ b/mail/mutt/patches/patch-ab
@@ -1,8 +1,17 @@
-$NetBSD: patch-ab,v 1.15 2010/04/10 16:08:51 tron Exp $
+$NetBSD: patch-ab,v 1.17 2015/09/03 21:04:34 wiz Exp $
 
---- Makefile.in.orig	2007-05-27 02:00:00.000000000 +0100
-+++ Makefile.in	2010-04-10 16:54:51.000000000 +0100
-@@ -165,7 +165,7 @@
+--- Makefile.in.orig	2015-08-30 17:24:26.000000000 +0000
++++ Makefile.in
+@@ -110,7 +110,7 @@ CONFIG_CLEAN_FILES = intl/Makefile hcach
+ CONFIG_CLEAN_VPATH_FILES =
+ am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(bindir)"
+ PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)
+-am_mutt_OBJECTS = addrbook.$(OBJEXT) alias.$(OBJEXT) attach.$(OBJEXT) \
++am_mutt_OBJECTS = mvchgat.$(OBJEXT) addrbook.$(OBJEXT) alias.$(OBJEXT) attach.$(OBJEXT) \
+ 	base64.$(OBJEXT) browser.$(OBJEXT) buffy.$(OBJEXT) \
+ 	color.$(OBJEXT) crypt.$(OBJEXT) cryptglue.$(OBJEXT) \
+ 	commands.$(OBJEXT) complete.$(OBJEXT) compose.$(OBJEXT) \
+@@ -329,7 +329,7 @@ DATADIRNAME = @DATADIRNAME@
  DBX = @DBX@
  DEBUGGER = @DEBUGGER@
  DEFS = -DPKGDATADIR=\"$(pkgdatadir)\" -DSYSCONFDIR=\"$(sysconfdir)\" \
@@ -11,31 +20,23 @@ $NetBSD: patch-ab,v 1.15 2010/04/10 16:08:51 tron Exp $
  	-DHAVE_CONFIG_H=1
  
  DEPDIR = @DEPDIR@
-@@ -266,7 +266,7 @@
- install_sh = @install_sh@
- libdir = @libdir@
- libexecdir = @libexecdir@
--localedir = @localedir@
-+localedir = /usr/pkg/share/locale
- localstatedir = @localstatedir@
- mandir = @mandir@
- mkdir_p = @mkdir_p@
-@@ -908,8 +908,7 @@
- 
- install-data-am: install-data-local
- 
--install-exec-am: install-binPROGRAMS install-binSCRIPTS \
--	install-exec-local
-+install-exec-am: install-binPROGRAMS install-binSCRIPTS
- 
- install-info: install-info-recursive
- 
-@@ -987,7 +986,7 @@
+@@ -799,6 +799,7 @@ distclean-compile:
+ @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/rfc2231.Po@am__quote@
+ @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/rfc3676.Po@am__quote@
+ @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/rfc822.Po@am__quote@
++@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/mvchgat.Po@am__quote@
+ @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/safe_asprintf.Po@am__quote@
+ @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/score.Po@am__quote@
+ @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/send.Po@am__quote@
+@@ -1338,11 +1339,6 @@ install-exec-hook:
+ 		rm -f $(DESTDIR)$(bindir)/mutt.dotlock ;		\
  		ln -sf $(DESTDIR)$(bindir)/mutt_dotlock $(DESTDIR)$(bindir)/mutt.dotlock ; \
  	fi
- 	if test -f $(DESTDIR)$(bindir)/mutt_dotlock && test x@DOTLOCK_GROUP@ != x ; then \
--		chgrp @DOTLOCK_GROUP@ $(DESTDIR)$(bindir)/mutt_dotlock && \
-+		$(CHGRP) @DOTLOCK_GROUP@ $(DESTDIR)$(bindir)/mutt_dotlock && \
- 		chmod @DOTLOCK_PERMISSION@ $(DESTDIR)$(bindir)/mutt_dotlock || \
- 		{ echo "Can't fix mutt_dotlock's permissions!" >&2 ; exit 1 ; } \
- 	fi
+-	if test -f $(DESTDIR)$(bindir)/mutt_dotlock && test x$(DOTLOCK_GROUP) != x ; then \
+-		chgrp $(DOTLOCK_GROUP) $(DESTDIR)$(bindir)/mutt_dotlock && \
+-		chmod $(DOTLOCK_PERMISSION) $(DESTDIR)$(bindir)/mutt_dotlock || \
+-		{ echo "Can't fix mutt_dotlock's permissions!  This is required to lock mailboxes in the mail spool directory." >&2 ; exit 1 ; } \
+-	fi
+ 
+ install-data-local:
+ 	$(MKDIR_P) $(DESTDIR)$(sysconfdir)
